# Generated by Django 5.2 on 2025-04-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'ordering': ['brand', 'name']},
        ),
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='condition',
            field=models.CharField(default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='display_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='graphics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
