# Generated by Django 5.2 on 2025-04-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_laptop_options_alter_laptop_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
