# Generated by Django 5.2 on 2025-04-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_laptop_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='performance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
