# Generated by Django 5.2 on 2025-04-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review_performance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
