# Generated by Django 5.2 on 2025-05-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
